M48
; DRILL file KiCad 10.0.1 date 2026-06-25T17:46:57
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-25T17:46:57-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X127.5Y-59.25
X132.0Y-59.25
T2
X54.6Y-100.5
X55.012Y-55.245
X135.4Y-100.5
X135.65Y-54.55
M30
